set(hci_rpmsg_KERNEL_HEX_NAME zephyr.hex)
set(hci_rpmsg_ZEPHYR_BINARY_DIR C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr)
set(hci_rpmsg_KERNEL_ELF_NAME zephyr.elf)
list(APPEND hci_rpmsg_BUILD_BYPRODUCTS C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr/zephyr.hex)
list(APPEND hci_rpmsg_BUILD_BYPRODUCTS C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr/zephyr.elf)
set(nrf5340pdk_nrf5340_cpunet_PM_DOMAIN_PARTITIONS C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr/../partitions_nrf5340pdk_nrf5340_cpunet.yml)
set(nrf5340pdk_nrf5340_cpunet_PM_DOMAIN_REGIONS C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr/../regions_nrf5340pdk_nrf5340_cpunet.yml)
set(nrf5340pdk_nrf5340_cpunet_PM_DOMAIN_HEADER_FILES C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr/include/generated/pm_config.h)
set(nrf5340pdk_nrf5340_cpunet_PM_DOMAIN_IMAGES nrf5340pdk_nrf5340_cpunet:hci_rpmsg)
set(nrf5340pdk_nrf5340_cpunet_PM_HEX_FILE C:/Users/cafo/ncs/my_ncs/ncs/nrf/samples/bluetooth/central_uart/build_nrf5340pdk_nrf5340_cpuapp/hci_rpmsg/zephyr/merged_nrf5340pdk_nrf5340_cpunet.hex)
